---
title: "qstacktseries"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{qstacktseries}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(timeseries)
library(gapminder)
library(dplyr)
```

This is how the function `qstacktseries` works: 

Building a stacked area time series plot with a dummy data set:

```{r dataset}
  testdf <- data.frame(year = rep(seq(from = 1980, to= 1990, 1), 3),
                       rainfall = c(runif(11, 0, 100), rnorm(11, 70, 10),
                                    rnorm(11, 20, 20)),
                       temp = c(rnorm(11, 70, 30), rnorm(11, 45, 20), 
                                rnorm(11, 100, 10)),
                       daysofsun = c(NA, NA, rnorm(9, 280, 50), rnorm(11, 300, 30), NA, 
                                     rnorm(10, 340, 15)),
                       region = c(rep("A",11), rep("B", 11), rep("C", 11)))
```

```{r example 1}
qstacktseries(testdf, year, rainfall, region, verbose = TRUE)
```
Building a stacked area time series plot with a pre-existing data set: *gapminder*

```{r example 2}
qstacktseries(gapminder %>%
                filter(continent == "Asia"), year, gdpPercap, country, verbose = TRUE)
```
These are some errors you might see if `qstacktseries` is given non-numeric input for the *time* or *voi* inputs: 

```{r example 3: Errors, error=TRUE}

qstacktseries(gapminder %>%
                filter(continent == "Asia"),continent, pop, country, verbose = TRUE)

qstacktseries(gapminder %>%
                filter(continent == "Africa"), year, country, continent, verbose = TRUE)
```

