---
title: "qtseries"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{qtseries}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(timeseries)
library(gapminder)
library(dplyr)
```

This is how the function `qtseries` works: 

Building a time series plot with a dummy data set:

```{r dummy dataset setup}
testdf <- data.frame(year = rep(seq(from = 1980, to= 1990, 1), 3),
                       rainfall = c(rnorm(11, 100, 30), rnorm(11, 70, 10),rnorm(11, 20, 20)),
                       temp = c(rnorm(11, 70, 30), rnorm(11, 100, 10),rnorm(11, 45, 20)),
                       daysofsun = c(NA, NA, rnorm(9, 280, 50), rnorm(11, 300, 30), NA, rnorm(10, 340, 15)),
                       region = c(rep("A",11), rep("B", 11), rep("C", 11)))
```

```{r example 1}
qtseries(testdf, year, daysofsun, region, verbose = TRUE)
```

Building a time series plot with the *gapminder* data set: 

```{r example 2}
qtseries(gapminder %>%
            filter(continent == "Europe"), year, pop, country, verbose = TRUE)
```

Some errors you might see if `qtseries` is given non-numeric variables for the *time* or *voi* inputs: 

```{r example 3: Errors, error=TRUE}
qtseries(gapminder %>%
            filter(continent == "Americas"),continent, pop, country, verbose = TRUE)

qtseries(gapminder %>%
              filter(continent == "Europe"),year, country, continent, verbose = TRUE)
```
